### ISSUE TITLE
linux is throwing way to many errors

### ISSUE THREAD

**Issue by EvelynMakesThings** [GameEngineering/EP01_SandSim#4]
I am using linux on chromebook and I would like to say, this is not letting me do the gcc compiler thing no matter what i try!
I did make some changes to the code of it because it was spitting out the file not found error foursome reason
![Screenshot 2022-09-20 3 05 00 PM](https://user-images.githubusercontent.com/99486014/191354018-72570b55-743d-486a-90b2-a0f9b5ecc4c8.png)
![Screenshot 2022-09-20 3 07 12 PM](https://user-images.githubusercontent.com/99486014/191354422-3279aed6-e678-40cc-8242-ab6b5749b71a.png)

**Comment by A2d3e2** [comment]
just so you know i used git clone instead of the official GitHub CLI

**Comment by EvelynMakesThings** [comment]
oh, never mind, can you just change the file name  of ./proc/linux/compile_linux_gcc.sh to gcc.sh like in the install instructions?
